apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: http  # FIX: point to the named container port
